### ISSUE TITLE
Console Spam Error

### ISSUE THREAD

**Issue by AkroDogy** [austinpilz/ServerSync#5]
When i join, the console are spammed with this:

[ServerSync] Task #396 for ServerSync v1.6.3 generated an exception
java.lang.NullPointerException
        at com.AustinPilz.ServerSync.Vault.VaultUpdate.run(VaultUpdate.java:22) ~[?:?]
        at org.bukkit.craftbukkit.v1_8_R3.scheduler.CraftTask.run(CraftTask.java:71) ~[Lobby.jar:git-Spigot-db6de12-18fbb24]
        at org.bukkit.craftbukkit.v1_8_R3.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:350) [Lobby.jar:git-Spigot-db6de12-18fbb24]
        at net.minecraft.server.v1_8_R3.MinecraftServer.B(MinecraftServer.java:723) [Lobby.jar:git-Spigot-db6de12-18fbb24]
        at net.minecraft.server.v1_8_R3.DedicatedServer.B(DedicatedServer.java:374) [Lobby.jar:git-Spigot-db6de12-18fbb24]
        at net.minecraft.server.v1_8_R3.MinecraftServer.A(MinecraftServer.java:654) [Lobby.jar:git-Spigot-db6de12-18fbb24]
        at net.minecraft.server.v1_8_R3.MinecraftServer.run(MinecraftServer.java:557) [Lobby.jar:git-Spigot-db6de12-18fbb24]
        at java.lang.Thread.run(Unknown Source) [?:1.8.0_181]

**Comment by AkroDogy** [comment]
Plugins on server: LuckPerms, SuperTrails, CustomList, Skript, PlaceholderAPI, FeatherBoard, SkQuery, ViaVersion, HolographicDisplays, Tablist, Vault, PlayerPoints, Citizens, CrazyCrates, skRayFall, DeluxeMenus, CommandNPC, ServerSync

**Comment by austinpilz** [comment]
Hey Akro, did this issue just start? It looks like you’re running 1.8. I don’t see any reason why ServerSync wouldn’t work with 1.8, but it was never designed to work on 1.8 to begin with. 

You didn’t list Vault as one of the plugins on your server. ServerSync uses Vault to sync currencies, and that’s where the error is occurring. Install Vault.

**Comment by AkroDogy** [comment]
I have vault installed

**Comment by asaasa123** [comment]
?? bump.

I'm using 1.12.2, it doesnt work for me either. it says i do not have vault installed but i do.

my version is 1.6.3
